config/routes.rb
Agora::Application.routes.draw do
  resources :memberships

  get 'submission_submission/:id', :to => 'submissions#view'
  get 'register', :to => 'users#new'
  post 'submissions', to: 'submissions#upload_message'
  match 'registrations/add_to_course_staff' => 'registrations#add_to_course_staff'
  match 'registrations/invite_students' => 'registrations#invite_students'
  match 'application/login_student' => 'application#login_student'
  match 'assignments/publish' => 'assignments#publish'
  match 'all_users' => 'users#all_users'

  get "users/new"
  get "users/edit"
  get "user_sessions/new"

  resources :courses do
    resources :assignments do
      get 'export', :controller => 'assignments', :action => 'export'
      resources :memberships
      resources :submissions do
        resources :evaluations do
          delete 'destroy', controller: 'reviews', action: 'destroy'
        end

      end

      resources :questions do
        resources :responses
        resources :scales
      end

      resources :reviews do
        get :assign_reviews, :on => :collection
        post :edit_review, :on => :collection
      end
      
    end
  end

  resources :password_resets, only: [:new, :create, :update]

  resources :registrations
  resources :evaluations

  resources :users do
    resources :emails, only: [:index, :show, :destroy]
    member do
      get :received
      post :resend_confirm_email
    end
  end

  get 'login', :controller => 'user_sessions', :action => 'new'  
  get 'logout', :controller => 'user_sessions', :action => 'destroy'  
  resources :user_sessions 

  root :to => 'courses#index'

  match 'users/:id/reset_password/:confirmation_token',
        to: 'password_resets#edit',
        as: :reset_password
  match '/signin',  to: 'user_sessions#new'
  match '/email_confirmation', to: 'static_pages#email_confirmation_sent'
  match 'users/:id/confirm/:confirmation_token',
        to: 'users#confirm_email',
        as: :confirm_email

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  require 'csv'
  require 'open-uri'

  before_filter :get_course
  load_and_authorize_resource :except => [:new, :create, :update ]
  skip_authorization_check :only => [:new, :create]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
    if current_user.instructor?(@course)
      if @assignment = @course.assignments.last
        @URL = course_assignment_url(@course, @assignment)
      else
        @URL = edit_user_path(current_user, :course => @course.id)     #default is settings page
      end
    else  #student
      if urgent = @course.to_do(current_user)[0]   # see if student has a to_do
        @URL = course_assignment_url(@course, urgent[:assignment])
      elsif (any = @course.assignments.select{|a| !a.draft }).length > 0
        @URL = course_assignment_path(@course, any.sort_by{|a| a.created_at }.last )     #show newest assignment
      else
        @URL = edit_user_path(current_user)     #go to settings page
      end
    end

    respond_to do |format|
      format.html { redirect_to(@URL) }
      format.json { render json: @assignments }
    end
  end

  def fix
    puts "Running fix"
    # testTeamSections
    # Response.check
    # admin = User.find_by_email('admin@email.com')
    # Course.all.each do |c|
    #   unless admin.registrations.any?{|r| r.course_id == c.id }
    #     Registration.new(course_id: c.id, user_id: admin.id, active:true, instructor: true, course_code: c.course_code).save!
    #   end
    # end
    # @assignment.memberships.each do |m|
    #   user_registration = @course.registrations.select{|r| r.user_id == m.user_id}[0]
    #   team_registration = @course.registrations.select{|r| r.user_id == m.pseudo_user_id}[0]
    #   team_registration.section = user_registration.section
    #   puts "reg: " + user_registration.inspect
    #   team_registration.save!
    #   end

    # registrants = Registration.all.select{|r| params[:course_id].to_i == r.course_id }
    # registrants.each do |r|
    #   rssubs = r.user.submissions.select{|s| s.assignment_id == params[:id].to_i }
    #   if rssubs.length > 1
    #     puts 'Error: ' + r.user.email + ' has multiple submissions:'
    #     rssubs.sort_by!{|s| s.created_at }
    #     rssubs.each{|s| puts '   ' + s.created_at.to_s }
    #     rssubs.first(rssubs.length - 1).each{|s|s.destroy }
    #   end
    # end
    #
    #
    # Submission.all.each do |s|
    #   if !s.url and s.attachment_file_name
    #     puts "Error: No url: " + (s.user ? s.user.email.inspect : '') + ' ' + s.attachment.url
    #     s.url = s.attachment.url.gsub('/system', 'https://s3.amazonaws.com/Coursemark')
    #     s.save!
    #   else
    #     puts "No attachment: " +  (s.user ? s.user.email.inspect : '')
    #   end
    # end
    file_count = 1
    Dir.chdir('/Users/jhm/Desktop/Submissions')
    @assignment.submissions.each do  |s|
      begin
        open('https:' + s.url, 'rb')  do |file|
           process_file(file, file_count)
           file_count = file_count + 1
          end
        end
        puts 'OK: ' + s.url
      # rescue
      #   puts 'Error, missing: ' + s.url + ' User: ' + s.user.name
      end
    #
    # end
    # count = 0
    # @assignment.submissions.each do  |s|
    #   if test_file(s)
    #     count += 1
    #   end
    # end
    # puts "Successful opens: " + count.to_s
    # @assignment.submissions.each do  |s|
    #   puts "Submission for: " +  s.user.email + " is " + s.inspect
    #   if !s.user.pseudo  # this was submitted before teams were assigned
    #     s.user.memberships.each do  |m|
    #       if m.assignment_id == s.assignment_id
    #         team_submission = Submission.new(assignment_id: s.assignment_id, user_id: m.pseudo_user_id,
    #                                          instructor_approved: false, url: s.url )
    #         team_submission.save!
    #         puts "Moved: " + s.user.email + "'s submission to " + User.find(m.pseudo_user_id).email
    #         s.destroy
    #       end
    #     end
    #
    #   end
    # team_submission = Submission.new(assignment_id: 32, user_id: 236,
    #                                   instructor_approved: false, url: "https://s3.amazonaws.com/Coursemark/UCRE_2014/160/Team_Contract.pdf" )
    #  team_submission.save!
    #  team_submission = Submission.new(assignment_id: 40, user_id: 236,
    #                                   instructor_approved: false, url: "https://s3.amazonaws.com/Coursemark/UCRE_2014/177/Flow_Consolidation.pdf" )
    #  team_submission.save!
    #  team_submission = Submission.new(assignment_id: 39, user_id: 236,
    #                                    instructor_approved: false, url: "https://s3.amazonaws.com/Coursemark/UCRE_2014/177/Sequence_Consolidation.pdf" )
    #  team_submission.save!
    # Membership.new(team:'A-4', user_id: 101, assignment_id: @assignment.id, pseudo_user_id: 395).save!
    # Membership.new(team:'A-4', user_id: 120, assignment_id: @assignment.id, pseudo_user_id: 395).save!
    # Membership.new(team:'A-4', user_id: 116, assignment_id: @assignment.id, pseudo_user_id: 395).save!
    # Membership.new(team:'A-4', user_id: 109, assignment_id: @assignment.id, pseudo_user_id: 395).save!
    # Membership.new(team:'A-4', user_id: 102, assignment_id: @assignment.id, pseudo_user_id: 395).save!
    #
    # @assignment.submissions.each do  |s|
    #   puts "Submission for: " +  s.user.email + " is " + s.inspect
    # end
    # students = @course.registrations.select{|r| r.user.pseudo and @assignment.memberships.any?{|m| m.pseudo_user_id == r.user_id } }.map{|r| r.user }
    # students.each do |student|
    #   puts "student: " +  student.email
    # end

    # User.all.each do |user|
    #   if user.pseudo? and user.submissions.length == 0
    #     puts "Deleting " + user.name
    #     Membership.all.each{|m| if m.pseudo_user_id == user.id then m.destroy end }
    #     user.destroy
    #   end
    # end

    # User.all.each do |user|
    #   if user.pseudo? and user.submissions.length == 0
    #     puts 'Destroying user: ' + user.email
    #   end
    # end

    # @assignment.memberships.each do |membership|
    #    puts 'Membership ' + membership.inspect
    # end

  end

  def process_file (file, count)
    ofile = File.new(count.to_s + '.pdf', 'wb+')
    ofile.write(file.read)
    ofile.close
  end

  def testTeamSections
    @assignment.memberships.each do |m|
      team = User.find(m.pseudo_user_id)
      student = User.find(m.user_id)
      if getSection(team) != getSection(student)
        puts 'Section mistake for ' + team.email + ' (' + getSection(team) + ') vs. ' + student.email   + ' (' + getSection(student) + ')'
      end
    end
  end

  def getSection(user)
    @course.registrations.each do |r|
      if r.user_id == user.id
        return r.section
      end
    end
  end


  def deleteOrphanedResponses

    User.all.each do |u|
      if u.pseudo
        ok = false
        Membership.all.each do |m|
          if m.pseudo_user_id == u.id
            ok = true
            break
          end
        end
        unless ok
          puts 'Error: Destroying pseudo user ' + u.email
          u.destroy
        end
      end
    end
  end


  # def test_file(s)
  #   begin
  #     if !s.url=~/^https?:\/\//
  #       puts "Bad url: " + s.url + ' for ' + s.user_id
  #       s.url = "https:#{s.url}"
  #       s.save!
  #       open(s.url)
  #     end
  #     true
  #   rescue
  #     puts 'Error, missing: ' + s.url.inspect + ' User: ' + s.user.name + ' ' + s.user.id.to_s
  #     false
  #   end
  # end


  def vanilla(s)
    s.gsub(/[ :]/, '_')
  end

  # GET /assignments/1

  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])
    @course = @assignment.course
    @user = current_user
    if @user.instructor?(@course)
      if params[:fix]
        fix
      end
      if reviewer_id = params[:reviewer]
        @reviewer = User.find(reviewer_id)
        @reviewing_tasks = @assignment.evaluations.forUser(@reviewer)
        render 'assignments/show_instructor'
        return
      else
        redirect_to(edit_course_assignment_url(@course, @assignment))
        return
      end
    end

    # User is a student. Create 'To Do' List
    @to_do = @course.to_do(current_user)

    @reviewing_tasks = @assignment.evaluations.forUser(current_user).sort_by{|t| t.created_at}
    if Time.zone.now > @assignment.review_due     # allow late reviewing until instructor ends
      @reviewing_tasks = @reviewing_tasks.select{|r| r.finished or !r.submission.instructor_approved }
    end
    @submissions = @assignment.get_submissions(current_user)
    @submission = @submissions.sort_by{|s| s.created_at }.last
    unless @submission
      @submission = Submission.new(assignment_id: @assignment.id)
    end
    @questions = @assignment.questions.sort_by{|q| q.created_at }
    @teams = @user.memberships.select{|m| m.assignment.course_id == @course.id and m.assignment_id == @assignment.id }.
        map{|m| User.find(m.pseudo_user_id)}

    @s3_direct_post = S3_BUCKET.presigned_post(
        key: vanilla(@course.name) + '/' + @user.id.to_s + '/' + vanilla(@assignment.name) + '.pdf',
        success_action_status: 201,
        acl: :public_read,
        content_type: 'application/pdf')       # For uploads. It will be filed under the human (not team) user id.

    respond_to do |format|
      format.html
      format.json {render json: @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    if !current_user.instructor?(@course)
      return
    end

    @assignment = Assignment.new
    @assignment.name = "New Assignment"
    @assignment.reviews_required = 4

    if @course.get_students.length <= 4
      @assignment.reviews_required = @course.get_students.length - 1
    end

    if @assignment.reviews_required <= 0
      @assignment.reviews_required = 0
    end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<% if @assignment.errors.any? %>

    <div id="error_explanation">
      <% @assignment.errors.messages.values.each do |msgs| %>
          <% msgs.each do |msg| %>
              <p><%= msg %></p>
          <%end %>
      <% end %>
    </div>
<% end %>

<%= nested_form_for [@course, @assignment] do |f| %>
    <h3>Assignment Settings</h3>

    <div class="field">
      <%= f.label :name, "Assignment Name" %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :submission_due, "Submission Deadline" %><br />
      <%= f.text_field :submission_due_date %> at
      <%= f.time_select :submission_due_time, {minute_step: 5, ampm: true, :time_separator => ""} %>
    </div>
    <div class="field">
      <%= f.label :review_due, "Review Deadline" %><br />
      <%= f.text_field :review_due_date %> at
      <%= f.time_select :review_due_time, {minute_step: 5, ampm: true, :time_separator => ""} %>
    </div>
    <div class="field">
      <%= f.label :reviews_required, 'Reviews per Submission' %><br />
      <%= f.number_field :reviews_required, :disabled => @assignment.review_due && (Time.zone.now > @assignment.submission_due) %>
    </div>
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="field">
      <%= f.label :team_submissions, "Team Submissions" %>&nbsp;
      <%= f.check_box :team, :disabled => !@assignment.draft %>
    </div>
    <div class="clearfix"></div>
    <div class="field">
      <%= f.label :manual_assignment, 'Wait for \'Start Reviews\'' %>&nbsp;
      <%= f.check_box :manual_assignment, :disabled => @assignment.review_due && (Time.zone.now > @assignment.submission_due), value: @assignment.manual_assignment %>
    </div>
    <div class="field">
      <%= f.label :draft, 'Draft' %>&nbsp;
      <%= f.check_box :draft, value: @assignment.draft %>
    </div>
    <div class="actions">
      <div class="clearfix"></div>
      <%= f.submit value:'Update' %>
    </div>
    <% if @assignment.id %>
        <div class="actioms">
          <%= f.submit value:'End All Activity' %>
          <!--<%= link_to 'End All Activity', course_assignment_path(@course, @assignment), method: :end %>-->
        </div>
    <% end %>
    <div class="clearfix"></div>
    <% if @assignment.id %>
        <div class="delete">
          <%= link_to 'Delete', course_assignment_path(@course, @assignment), method: :delete, data: { confirm: 'Are you sure you want to delete this assignment?' } %>
        </div>
    <% end %>
    <br>
    <div class="delete">
      <%= "<a href=/courses/#{@course.id}/assignments/#{@assignment.id}?fix=true>Fix </a>".html_safe  %>
    </div>
<% end %>

app/views/assignments/_header.html.erb
<div id="header">

  <% if @assignment %>
      <h1 class="name"><%= @assignment.name %></h1>

      <% if @assignment.id %>
          <div class="tabs" style="width:100%;float:left" >
            <% if current_user.instructor?(@course) %>
                <div class="tab <%= 'active' if controller.controller_name == 'assignments' %>">
                  <%= link_to edit_course_assignment_path(@course, @assignment) do %>
                      Dashboard
                  <% end %>
                </div>

                <div class="tab <%= 'active' if controller.controller_name == 'reviews' %>">
                  <%= link_to course_assignment_reviews_path(@course, @assignment) do %>
                      Reviews
                  <% end %>
                </div>

                <div class="tab <%= 'active' if controller.controller_name == 'submissions' %>">
                  <%= link_to course_assignment_submissions_path(@course, @assignment) do %>
                      Submissions
                  <% end %>
                </div>

                <div class="tab <%= 'active' if controller.controller_name == 'questions' %>">
                  <%= link_to course_assignment_questions_path(@course, @assignment) do %>
                      Rubric
                  <% end %>
                </div>

                <% if @assignment.team %>
                    <div class="tab <%= 'active' if controller.controller_name == 'memberships' %>">
                      <%= link_to course_assignment_memberships_path(@course, @assignment) do %>
                          Teams
                      <% end %>
                    </div>
                <% end %>

            <% end %>
      <% end %>

      <div class="tab settings">
        <%= link_to edit_user_path(current_user, :course => @course.id) do %>
            Settings
        <% end %>
      </div>
      <div class="tab logout">
        <%= link_to logout_path do %>
            Sign out
        <% end %>
      </div>
      </div>
  <% end %>

</div>

<div id="headerSpacer"></div>

app/views/assignments/_submission.html.erb
<%= form_for [@course, @assignment], html: {class: 'submissionUpload'} do |f| %>
    <h3>Submit Assignment</h3>
    <% if @teams.length > 1 %>
        <select id="teams">
          <option value='-1' >Select Submitting Team</option>
          <% @teams.each do |t| %>
              <option value="<%= t.id %>" ><%= t.name %></option>
          <% end %>
        </select>
    <% end %>
    <% if !@submission.url.blank?  %>
            A file has been submitted. Please click <%= link_to 'this', @submission.url, :target => "_blank" %> to ensure that it is readable. You may re-submit until the deadline.
    <% end %>
    <div class="field">
      <%= f.file_field :url, :accept => 'application/pdf', :required => true, :style => 'border: 0px' %>
    </div>
    <div class="field">
      <%= f.hidden_field :assignment_id, value: @assignment.id %>
    </div>
    <div id='team' class="field">
      <%= f.hidden_field :user_id, value: @teams.length == 1 ? @teams[0].id : @user.id %>    <!-- value will be overwritten if multi-team assignment -->
    </div>
    <div class="actions">
      <script>
          function get_team() {
              var e = document.getElementById("teams");
              var selected_team = e.options[e.selectedIndex].value;
              document.getElementById("assignment_user_id").value =  selected_team;
          }
      </script>

      <button class="med_width_button button" name="commit" type="submit" onclick="get_team();" value="Submit" >Submit</button>

    </div>
    <!--
    <% if @submission.created_at %>
          <div class="edit_submission afterDeadline">
            <a href='<%= @submission.url %>' style="color:#343F53;">Check Submission</a>
          </div>
      <% end %>
    -->
<% end %>


<script>
      $(function() {
          $('.submissionUpload').find("input:file").each(function(i, elem) {
              var fileInput    = $(elem);
              var form         = $(fileInput.parents('form:first'));
              var submitButton = form.find('input[type="submit"]');
              var progressBar  = $("<div class='bar'></div>");
              var barContainer = $("<div class='progress'></div>").append(progressBar);
              fileInput.after(barContainer);
              fileInput.fileupload({
                  fileInput:       fileInput,
                  url:             '<%= @s3_direct_post.url %>',
                  type:            'POST',
                  autoUpload:       true,
                  formData:         <%= @s3_direct_post.fields.to_json.html_safe %>,
                  paramName:        'file', // S3 does not like nested name fields i.e. name="user[avatar_url]"
                  dataType:         'XML',  // S3 returns XML if success_action_status is set to 201
                  replaceFileInput: false,
                  progressall: function (e, data) {
                      var progress = parseInt(data.loaded / data.total * 100, 10);
                      progressBar.css('width', progress + '%')
                  },
                  start: function (e) {
                      var data = { assignment_id: <%= @assignment.id %>, user_id: <%= @user.id %> };
                      $.post("/submissions", data);
                      console.log("Starting Upload");
                      submitButton.prop('disabled', true);

                      progressBar.
                              css('background', 'green').
                              css('color', 'white').
                              css('border-radius', '6px').
                              css('padding', '5px').
                              css('display', 'block').
                              css('width', '0%').
                              text("Loading...");

                  },
                  done: function(e, data) {
                      submitButton.prop('disabled', false);
                      submitButton.removeClass('hidden');

                      progressBar.text("Uploaded: Ready to submit");

                      // extract key and generate URL from response
                      var key   = $(data.jqXHR.responseXML).find("Key").text();
                      var url   = '//<%= @s3_direct_post.url.host %>/Coursemark/' + key;

                      // create hidden field
                      var input = $("<input />", { type:'hidden', name: fileInput.attr('name'), value: url })
                      form.append(input);
                  },
                  fail: function(e, data) {
                      var data1 = { assignment_id: <%= @assignment.id %>, user_id: <%= @user.id %>, error: e.type  };
                      console.log("Error, Upload Failed: ", e, data);
                      $.post("/submissions", data1);
                      submitButton.prop('disabled', false);

                      progressBar.
                              css("background", "red"). 
                              css('color', 'white').
                              css('border-radius', '6px').
                              css('padding', '5px').
                              css('width', '100%').
                              text("Failed, check credentials");
                  }
              });
          });
      });
  </script>

app/views/assignments/edit.html.erb
<%= render "assignments/header" %>

<%= render 'form' %>

<div class="assignmentStatus">
	<h3>Assignment Progress</h3>
    <% @assignment = Assignment.find(@assignment.id) %> <!-- in case a validation error -->
	<div class="checkPoint <%= if @assignment.questions.length > 0 then 'completed' end %>">Rubric Entered</div>
	<div class="checkPoint <%= if (!@assignment.draft) then 'completed' end %>">Assignment Published</div>
	<div class="checkPoint <%= if (!@assignment.draft) && (Time.zone.now > @assignment.submission_due) then 'completed' end %>">Submission Deadline Passed</div>
	<div class="checkPoint <%= if (!@assignment.draft) && (@assignment.are_reviewers_assigned) then 'completed' end %>">Peer Reviews Assigned</div>
	<div class="checkPoint <%= if (!@assignment.draft) && (Time.zone.now > @assignment.review_due) then 'completed' end %>">Review Deadline Passed</div>
	<div class="checkPoint <%= if (!@assignment.draft) && (@assignment.allGradesApproved?)  then 'completed' end %>">Assignment Grading Complete</div>
</div>

<% if @assignment.are_reviewers_assigned  %>
    <% if Time.zone.now.between?(@assignment.submission_due, @assignment.review_due) and @reviewing_tasks.length > 0 %>
        <div id="reviewing_tasks" style="clear:both">
          <br>
          <b>Reviewing Tasks</b>
          <% @reviewing_tasks.each_with_index do |task, index| %>
              <%= link_to course_assignment_submission_path(@course, @assignment, task.submission) do %>
                  <div class="reviewing_task highlighted" > <%= ((task.finished? or Time.zone.now > @assignment.review_due) ? 'See' : 'Complete') + ' Review ' + (index + 1).to_s %></div>
              <% end %>
          <% end %>
        </div>
    <% end %>
<% end %>

app/views/assignments/index.html.erb
<h1>Listing assignments</h1>

<table>
  <tr>
    <th>Submission due</th>
    <th>Review due</th>
    <th>Reviews required</th>
    <th>Draft</th>
    <th>Course</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.submission_due %></td>
    <td><%= assignment.review_due %></td>
    <td><%= assignment.reviews_required %></td>
    <td><%= assignment.draft %></td>
    <td><%= assignment.course_id %></td>
    <td><%= link_to 'Show', assignment %></td>
    <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
    <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<div id="header">
    <h1 class="name">New Assignment</h1>
    <div class="tabs">
        <div class="tab settings">
        	<%= link_to edit_user_path(current_user) do %>
                Settings
            <% end %>
        </div>
        <div class="tab logout">
            <%= link_to logout_path do %>
                Sign out
            <% end %>
        </div>
    </div>
</div>

<div id="headerSpacer" style="height:122px;"></div>

<%= render 'form' %>

app/views/assignments/show.html.erb
<%= render "assignments/header" %>

<!-- User is not instructor -->

  
    <!-- <span>Assignment Progress: </span>
    <% if (Time.zone.now > @assignment.submission_due)  %>
      Assignment due on <%= @assignment.submission_due.to_s(:pretty) %>
      <% elsif (@assignment.manual_assignment && @assignment.reviewers_assigned) || ((Time.zone.now > @assignment.submission_due) && (@assignment.reviews_required > 0) && !@assignment.manual_assignment) %>
      Peer reviews assigned
    <% elsif (Time.zone.now > @assignment.review_due) && (@assignment.reviews_required > 0)  %>
    Peer reviews due on <%= @assignment.review_due.to_s(:pretty) %>
    <% elsif (@submission.instructor_approved) && (@assignment.reviews_required > 0) %>">
    Grade approved
    <% else %>
    Assignment released
    <% end %> -->

<% if !@assignment.are_reviewers_assigned or (Time.zone.now < @assignment.review_due and @submissions.length == 0) %>    <!-- allow late submissions if none done -->
    <%= render 'submission' %>
<% end %>


<% if @submissions.length > 0 %>
    <h3 class='assignment_section_header'>Your Submission<%= @submissions.length > 1 ? 's' : '' %></h3>
    <% @submissions.each do |submission| %>
        <div class="reviewing_task your_submission">
          <%= link_to course_assignment_submission_path(@course, @assignment, submission) + '?view=true' do %>
              <%= submission.user.name %>
              <span>
                <%= ((n = submission.evaluations.select{|e| e.finished }.length) > 0 ? "#{n.to_s} review" : '') + (n > 1 ? 's' : '')  %>
              </span>
          <% end %>
        </div>
    <% end %>
<% end %>


<br><br>


<% if @assignment.are_reviewers_assigned and @reviewing_tasks.length > 0 %>
    <div id="reviewing_tasks">
      <% if @reviewing_tasks.length > 0 %>
          <h3 class='assignment_section_header'>Reviews by You</h3>
          <% @reviewing_tasks.each_with_index do |task, index| %>
              <div class="reviewing_task <%= (task.finished?  ? '' : 'highlighted') %> ">
                <%= link_to course_assignment_submission_path(@course, @assignment, task.submission) do %>
                    <%= task.finished?  ? 'See' : "Complete"  %>
                    <%= ' Review ' + (index + 1).to_s %>
                    <% if Time.now < @assignment.review_due %>
                      <% review_time_is = @assignment.review_due.strftime('%A (%-m/%-d) at %I:%M %p</span>') %>
                      <%= task.finished? ? ((e = task.submission.evaluations.select{|e| e.finished }.length) > 0 ? ("<span>#{e.to_s} review(s)</span>").html_safe : '') : ("<span>by #{review_time_is}</span>").html_safe %>
                    <% end %>
                <% end %>
              </div>
          <% end %>
      <% end %>
    </div>
<% end %>

<!--<div class="clearfix"></div>-->


<% if Time.zone.now < @assignment.submission_due %>
    <h3 class='assignment_section_header'>Reviewing Rubric</h3>
    <% @questions.each do |question| %>
        <div class='submissionQuestionBox clearfix'>
          <h2><%= question.question_text %></h2>
          <div class='possiblePoints'><%= question.question_weight %> Points</div>
          <ul class='rubricScale'>
            <% question.scales.sort_by{|s| s.value}.each do |scale|  %>
                <li><%= scale.value.to_s + '%: ' + scale.description  %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
<% end %>

app/views/assignments/show_instructor.html.erb
<!-- The student has done at least one review -->
<%= render "assignments/header" %>

<h3>Reviews Given by <%= @reviewer.name %></h3>

<% if Time.zone.now < @assignment.review_due %>
    Reviews can still come in.
<% end %>

<div id="reviewing_tasks">
  <% @reviewing_tasks.each_with_index do |task, index| %>
      <% if task.finished? %>
          <%= link_to course_assignment_submission_path(@course, @assignment, task.submission) + '?instructor_review_of=' + @reviewer.id.to_s do %>
              <div class="reviewing_task" >Review of <%= task.submission.user.name %></div>
          <% end %>
      <% end %>
  <% end %>

</div>