config/routes.rb
Agora::Application.routes.draw do
  resources :memberships

  get 'submission_submission/:id', :to => 'submissions#view'
  get 'register', :to => 'users#new'
  post 'submissions', to: 'submissions#upload_message'
  match 'registrations/add_to_course_staff' => 'registrations#add_to_course_staff'
  match 'registrations/invite_students' => 'registrations#invite_students'
  match 'application/login_student' => 'application#login_student'
  match 'assignments/publish' => 'assignments#publish'
  match 'all_users' => 'users#all_users'

  get "users/new"
  get "users/edit"
  get "user_sessions/new"

  resources :courses do
    resources :assignments do
      get 'export', :controller => 'assignments', :action => 'export'
      resources :memberships
      resources :submissions do
        resources :evaluations do
          delete 'destroy', controller: 'reviews', action: 'destroy'
        end

      end

      resources :questions do
        resources :responses
        resources :scales
      end

      resources :reviews do
        get :assign_reviews, :on => :collection
        post :edit_review, :on => :collection
      end
      
    end
  end

  resources :password_resets, only: [:new, :create, :update]

  resources :registrations
  resources :evaluations

  resources :users do
    resources :emails, only: [:index, :show, :destroy]
    member do
      get :received
      post :resend_confirm_email
    end
  end

  get 'login', :controller => 'user_sessions', :action => 'new'  
  get 'logout', :controller => 'user_sessions', :action => 'destroy'  
  resources :user_sessions 

  root :to => 'courses#index'

  match 'users/:id/reset_password/:confirmation_token',
        to: 'password_resets#edit',
        as: :reset_password
  match '/signin',  to: 'user_sessions#new'
  match '/email_confirmation', to: 'static_pages#email_confirmation_sent'
  match 'users/:id/confirm/:confirmation_token',
        to: 'users#confirm_email',
        as: :confirm_email

end

app/models/scale.rb
class Scale < ActiveRecord::Base
  attr_accessible :description, :question_id, :value

  # Relationships
  has_many :responses
  belongs_to :question

  def new
    value = 0
  end

  # Validations
  validates_numericality_of :value, only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100


end

app/controllers/scales_controller.rb
class ScalesController < ApplicationController
  before_filter :get_assignment, :get_course, :get_question
  load_and_authorize_resource

  # GET /scales
  # GET /scales.json
  def index
    @scales = Scale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scales }
    end
  end

  # GET /scales/1
  # GET /scales/1.json
  def show
    @scale = Scale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scale }
    end
  end

  # GET /scales/new
  # GET /scales/new.json
  def new
    @scale = Scale.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scale }
    end
  end

  # GET /scales/1/edit
  def edit
    @scale = Scale.find(params[:id])
  end

  # POST /scales
  # POST /scales.json
  def create
    @scale = Scale.new(params[:scale])

    respond_to do |format|
      if @scale.save
        format.html { redirect_to @scale, notice: 'Scale was successfully created.' }
        format.json { render json: @scale, status: :created, location: @scale }
      else
        format.html { render action: "new" }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scales/1
  # PUT /scales/1.json
  def update
    @scale = Scale.find(params[:id])

    respond_to do |format|
      if @scale.update_attributes(params[:scale])
        format.html { redirect_to @scale, notice: 'Scale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scales/1
  # DELETE /scales/1.json
  def destroy
    @scale = Scale.find(params[:id])
    @scale.destroy

    respond_to do |format|
      format.html { redirect_to scales_url }
      format.json { head :no_content }
    end
  end
end

def get_assignment
  if params[:assignment_id]
    @assignment = Assignment.find(params[:assignment_id])
  end
end

def get_course
  if params[:course_id]
    @course = Course.find(params[:course_id])
  end
end

def get_question
  if params[:question_id]
    @question = Question.find(params[:question_id])
  end
end

app/helpers/scales_helper.rb
module ScalesHelper
end

app/views/scales/_form.html.erb
<%= nested_form_for [@course, @assignment, @question, @scale]  do |f| %>

  <% if @scale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scale.errors.count, "error") %> prohibited this scale from being saved:</h2>

      <ul>
      <% @scale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.collection_select :question_id, Question.all, :id, :question_text, :prompt => "Select question..." %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scales/_scale_fields.html.erb
<div class="field">
  <%= f.text_field :description, :placeholder => "Optional Label" %>
  <%= f.text_field :value, size: 3  %> %
  <%= f.link_to_remove "Remove" %>
</div>

app/views/scales/edit.html.erb
<%= render "assignments/header" %>

<div id="backBar">
  <%= link_to 'Back to Rubric', :back %>
</div>

<h2>Editing scale</h2>

<%= render 'form' %>

app/views/scales/index.html.erb
<h1>Listing scales</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Description</th>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scales.each do |scale| %>
  <tr>
    <td><%= scale.value %></td>
    <td><%= scale.description %></td>
    <td><%= scale.question_id %></td>
    <td><%= link_to 'Show', scale %></td>
    <td><%= link_to 'Edit', edit_scale_path(scale) %></td>
    <td><%= link_to 'Destroy', scale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scale', new_course_assignment_question_scale_path(@course, @assignment, @question) %>

app/views/scales/new.html.erb
<%= render "assignments/header" %>

<div id="backBar">
  <%= link_to 'Back to Rubric', :back %>
</div>

<h2>New Scale</h2>

<%= render 'form' %>

app/views/scales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @scale.value %>
</p>

<p>
  <b>Description:</b>
  <%= @scale.description %>
</p>

<p>
  <b>Question:</b>
  <%= @scale.question_id %>
</p>


<%= link_to 'Edit', edit_scale_path(@scale) %> |
<%= link_to 'Back', scales_path %>