config/routes.rb
Agora::Application.routes.draw do
  resources :memberships

  get 'submission_submission/:id', :to => 'submissions#view'
  get 'register', :to => 'users#new'
  post 'submissions', to: 'submissions#upload_message'
  match 'registrations/add_to_course_staff' => 'registrations#add_to_course_staff'
  match 'registrations/invite_students' => 'registrations#invite_students'
  match 'application/login_student' => 'application#login_student'
  match 'assignments/publish' => 'assignments#publish'
  match 'all_users' => 'users#all_users'

  get "users/new"
  get "users/edit"
  get "user_sessions/new"

  resources :courses do
    resources :assignments do
      get 'export', :controller => 'assignments', :action => 'export'
      resources :memberships
      resources :submissions do
        resources :evaluations do
          delete 'destroy', controller: 'reviews', action: 'destroy'
        end

      end

      resources :questions do
        resources :responses
        resources :scales
      end

      resources :reviews do
        get :assign_reviews, :on => :collection
        post :edit_review, :on => :collection
      end
      
    end
  end

  resources :password_resets, only: [:new, :create, :update]

  resources :registrations
  resources :evaluations

  resources :users do
    resources :emails, only: [:index, :show, :destroy]
    member do
      get :received
      post :resend_confirm_email
    end
  end

  get 'login', :controller => 'user_sessions', :action => 'new'  
  get 'logout', :controller => 'user_sessions', :action => 'destroy'  
  resources :user_sessions 

  root :to => 'courses#index'

  match 'users/:id/reset_password/:confirmation_token',
        to: 'password_resets#edit',
        as: :reset_password
  match '/signin',  to: 'user_sessions#new'
  match '/email_confirmation', to: 'static_pages#email_confirmation_sent'
  match 'users/:id/confirm/:confirmation_token',
        to: 'users#confirm_email',
        as: :confirm_email

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  first_name             :string(255)
#  last_name              :string(255)
#  email                  :string(255)
#  password               :string(255)
#  password_confirmation  :string(255)
#  confirmed              :boolean         default(FALSE)
#  confirmation_token     :string(255)
#  password_reset_sent_at :datetime
#  pseudo                 :boolean



class User < ActiveRecord::Base
  acts_as_authentic
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :pseudo

  # Relationships
  has_many :evaluations, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :registrations, dependent: :destroy
  has_many :courses, :through => :registrations
  has_many :assignments, :through => :courses
  has_many :memberships, dependent: :destroy

  # Get all users except the given user
  scope :without_user, ->(user) {where("user_id != ?", user.id)}


  # Helpers
  def name
    self.first_name + ' ' + self.last_name
  end

  def instructor?(course)
    self.registrations.each do |registration|
      if registration.course_id == course.id
        if registration.instructor
          return true
        end
      end
    end

    return false
  end

  def send_password_reset
    generate_confirmation_token
    self.password_reset_sent_at = Time.zone.now
    save!(validate: false)

    UserMailer.password_reset(self).deliver
  end

  def generate_confirmation_token
    self.confirmation_token = SecureRandom.urlsafe_base64
  end

  def submitting_id(submission)
    ms = submission.assignment.memberships.select{|m| m.user_id == self.id }
    ms.each{|m| if submission.user_id == m.pseudo_user_id then return m.pseudo_user_id end }
    self.id
  end

  def registration_in(course)
    registrations.select{|r| r.user_id == self.id and course.id == r.course_id }[0]
  end


  # Active Record Callbacks
  before_save { |user|
    user.email = email ? email.downcase : nil
    if user.new_record?
      user.generate_confirmation_token
    end
  }

  #Validations
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password_confirmation, presence: true
  validates :password, presence: { on: :create }, length: { minimum: 8, allow_blank: true }
  validates_uniqueness_of :email

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login, :except => [:edit]
	load_and_authorize_resource

  def all_users
    @course = Course.all[0]
  end

  def destroy
    Membership.all.each{|m| if m.pseudo_user_id == @user.id then m.destroy end }
    @user.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end

  end

  # GET
  def new
		if current_user
			if !request.GET['course'].blank?
				@registration = Registration.new()
				@registration.active = true;
        @registration.instructor = false;
        @registration.user = @user
        @registration.course_code = params['course']
				@registration.course = Course.where(:course_code => params['course']).first or raise InvalidCourse
					
				respond_to do |format|
					if @registration.save
	        			format.html { redirect_to course_path(@registration.course) }
	        			format.json { render json: @registration, status: :created, location: @registration }
	        		else 
						    format.html { render action: "new" }
	        			format.json { render json: @registration.errors, status: :unprocessable_entity }
	        		end
	        	end 
        	end
	    else
			@user = User.new

      respond_to do |format|
        format.html { render :layout => 'startup_page' }
        format.json { render json: @course }
      end
		end
	end

  def edit
    @user = current_user
    @courses = @user.courses
    @course = @courses.first
    @registrations = @user.registrations

    if params[:course]
      @course = Course.find(params[:course])
      @assignments = @course.assignments.published
    end
  end

  # POST
  def create
    # Checks if user started to register
    params[:user][:email] =  params[:user][:email].downcase
    if !User.find_by_email(params[:user][:email])
      @user = User.new(params[:user])
      if @user.save
        respond_to do |format|
          # Tell the UserMailer to send a welcome Email after save
          flash[:success] = "Welcome to Coursemark."
          UserMailer.welcome_email_walk_on(@user).deliver
          format.html { redirect_to(email_confirmation_path(id: @user.id)) }
        end
      else
        respond_to do |format|
          format.html { render action: 'new', :layout => 'startup_page', flash: {error: 'Password and/or confirmation is wrong.' }}
        end
      end
    else
      respond_to do |format|
        format.html {
          flash.now[:error] = 'That email has already been registered.'
          render action: 'new', :layout => 'startup_page'}
      end
    end
  end

  def update
    @user = User.find(params[:id])
    @course = @user.courses.last!
    @registrations = current_user.registrations

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to edit_user_url, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET
  # Confirms the email address of a user by matching confirmation token
  def confirm_email
    confirmation_token = params[:confirmation_token]
    @user = User.find_by_id(params[:id])
    if @user.confirmed
      redirect_to root_path, notice: "You already validated your email"
    elsif @user.confirmation_token == confirmation_token
      @user.confirmed = true
      @user.save(validate: false)
      redirect_to login_path, flash: {success: "Your email is confirmed. Please login."}
    else
      redirect_to root_path, flash: { error: "Access denied"}
    end
  end

  # POST
  def resend_confirm_email
    @user = User.find(params[:id])
    UserMailer.welcome_email_walk_on(@user).deliver
    redirect_to email_confirmation_path(id: @user.id)
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <div class="editAccountFields">
    <div class="field">
      <%= f.text_field :first_name, :placeholder => "First Name" %>
    </div>
    <div class="field">
      <%= f.text_field :last_name, :placeholder => "Last Name" %>
    </div>
    <div class="field">
       <%= @user.email %>
    </div>
    <div class="field">
     <%= f.password_field :password, :placeholder => "New Password" %> 
    </div>
    <div class="field">
      <%= f.password_field :password_confirmation, :placeholder => "New Password Confirmation" %> 
    </div>
    <div class="actions">
      <%= f.submit "Update account", :class => 'update_account_btn' %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <% @user.errors.full_messages.each do |msg| %>
        <%= msg %><br>
      <% end %>
    </div>
  <% end %>

  <div class="newAccountFields">
    <div class="field">
      <%= f.text_field :first_name, :placeholder => "First Name" %>   
    </div>
    <div class="field">
      <%= f.text_field :last_name, :placeholder => "Last Name" %>   
    </div>
    <div class="field">
      <%= f.text_field :email, :placeholder => "Email" %>   
    </div>
    <div class="field">
      <%= f.password_field :password, :placeholder => "Password" %> 
    </div>
    <div class="field">
      <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %> 
    </div>
    <%= hidden_field_tag 'course', request.GET[:course] %>
    <div class="actions">
      <%= f.submit "Create account", :course => params[:code] %>
    </div>
  </div>
<% end %>

app/views/users/all_users.html.erb
<h1 class="name">All Users</h1>


<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>ID</th>
    <th>&nbsp;</th>
  </tr>

  <% User.all.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.id.to_s %></td>
        <td><%= link_to 'Remove', user, method: :delete, data: { confirm: 'Are you sure you wish to remove this user from Coursemark?' }  %></td>
  </tr>
  <% end %>
</table>

app/views/users/confirm_email.html.erb
<% provide(:title, "Confirm Email") %>
  <center>
    Your email address, <%= @user.email %>, is confirmed.
  </center>
  <br/>
  <center>
    Click
    <%= link_to "here", signin_path %>
    to sign in.
  </center>

app/views/users/confirm_email.html.haml
.loginWrapper
- unless flash[:error]
  %p
    Thank you, #{@user.first_name}, for registering with Coursemark.
  %p
    Click
    = link_to "here", signin_path
    to sign in.
-else
  %h2
    No touching what isn't yours.

app/views/users/edit.html.erb
<div id="header">
  <h1 class="name">Account Settings</h1>
  <div class="tabs">
    <div class="tab settings">
      <%= link_to edit_user_path(current_user) do %>
          Settings
      <% end %>
    </div>
    <br>
    <div class="tab logout">
      <%= link_to logout_path do %>
          Sign out
      <% end %>
    </div>
  </div>
</div>

<div id="headerSpacer" style="height:90px;"></div>

<h2>Enrollments</h2>

<table>
  <tr>
    <th>Course</th>
    <th>Type</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>

<% @registrations.each do |registration| %>
  <tr>
    <% assignments = registration.course.assignments.select{ |a| !a.draft } %>
    <td><%= link_to registration.course.name, course_path(registration.course) %><%= assignments.length == 0 ? ' (No Assignments Yet)' : '' %></td>
    <td><%= registration.instructor ? "Course Staff" : "Student"  %></td>
    <td><%= link_to 'Leave Course', registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% if current_user.email == 'admin@email.com' %>
        <td><%= link_to 'Delete Course', registration.course, method: :delete, data: { confirm: 'Do you want to erase this course and all its data?' }%></td>
    <% else %>
        <td></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<% if @user.email == 'admin@email.com' %>
    <%= link_to new_course_path do %>
      <div class="button med_width_button" style="float:left;">Create Course</div>
    <% end %>

    <%= link_to '/all_users' do %>
        <div class="button med_width_button" style="float:left;">Show All Users</div>
    <% end %>

<% end %>

<%= link_to new_registration_path do %>
    <div class="button med_width_button" style="float:left;">Join Course</div>
<% end %>

<div class="clearfix"></div>

<h2>Login information</h2>

<%= render 'edit_form' %>

app/views/users/new.html.erb
<%= render 'form' %>