config/routes.rb
Agora::Application.routes.draw do
  resources :memberships

  get 'submission_submission/:id', :to => 'submissions#view'
  get 'register', :to => 'users#new'
  post 'submissions', to: 'submissions#upload_message'
  match 'registrations/add_to_course_staff' => 'registrations#add_to_course_staff'
  match 'registrations/invite_students' => 'registrations#invite_students'
  match 'application/login_student' => 'application#login_student'
  match 'assignments/publish' => 'assignments#publish'
  match 'all_users' => 'users#all_users'

  get "users/new"
  get "users/edit"
  get "user_sessions/new"

  resources :courses do
    resources :assignments do
      get 'export', :controller => 'assignments', :action => 'export'
      resources :memberships
      resources :submissions do
        resources :evaluations do
          delete 'destroy', controller: 'reviews', action: 'destroy'
        end

      end

      resources :questions do
        resources :responses
        resources :scales
      end

      resources :reviews do
        get :assign_reviews, :on => :collection
        post :edit_review, :on => :collection
      end
      
    end
  end

  resources :password_resets, only: [:new, :create, :update]

  resources :registrations
  resources :evaluations

  resources :users do
    resources :emails, only: [:index, :show, :destroy]
    member do
      get :received
      post :resend_confirm_email
    end
  end

  get 'login', :controller => 'user_sessions', :action => 'new'  
  get 'logout', :controller => 'user_sessions', :action => 'destroy'  
  resources :user_sessions 

  root :to => 'courses#index'

  match 'users/:id/reset_password/:confirmation_token',
        to: 'password_resets#edit',
        as: :reset_password
  match '/signin',  to: 'user_sessions#new'
  match '/email_confirmation', to: 'static_pages#email_confirmation_sent'
  match 'users/:id/confirm/:confirmation_token',
        to: 'users#confirm_email',
        as: :confirm_email

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_filter :get_assignments
  layout false
  load_and_authorize_resource

  # GET /courses
  # GET /courses.json
  def index
    puts 'Login: ' + current_user.email
    @courses = current_user.courses
    if @courses.length == 1
      @URL = @courses[0]
    else
      @URL = edit_user_path [current_user]
    end

    respond_to do |format|
      format.html { redirect_to(@URL) }
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
    current_user.registrations.each{|r| if r.course_id == @course.id  then r.active = true; r.save! end }
    Assignment.order(:submission_due)
    @assignments = @course.assignments.select{|a| !a.draft or current_user.instructor?(@course) }

    respond_to do |format|
      if current_user.instructor?(@course)
        format.html { redirect_to course_assignments_path(@course) }
      else
        format.html {render layout: 'application'}
      end
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create

    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        @registration = Registration.new
        @registration.active = true
        @registration.user = current_user
        @registration.course = @course
        @registration.course_code = @course.course_code
        @registration.instructor = true
        @registration.save!
        admin = User.find_by_email('admin@email.com')
        @registration = Registration.new
        @registration.active = true
        @registration.user = admin
        @registration.course = @course
        @registration.course_code = @course.course_code
        @registration.instructor = true
        @registration.save!

        format.html { redirect_to @course }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])

    @course.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :placeholder => "Course Name" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/_header.html.erb
<div id="header">

  <% if @course.id %>
      <h1 class="name"><%= @course.name %></h1>
      <div class="tabs" style="width:100%;float:left" >

        <div class="tab settings">
          <%= link_to edit_user_path(current_user, :course => @course.id) do %>
              Settings
          <% end %>
        </div>
        <div class="tab logout">
          <%= link_to logout_path do %>
              Sign out
          <% end %>
        </div>
      </div>
  <% end %>

</div>

<div id="headerSpacer"></div>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.name %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Coursemark | Login</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

      <link rel="stylesheet" href="/css/normalize.min.css">
        <link rel="stylesheet" href="/css/main.css">
        <link rel="shortcut icon" href="/favicon.png" />

        <script src="/js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
        <div class="loginWrapper newCourse">
            <div class="logo"><%= image_tag "coursemark.png", alt: "Coursemark" %></div>
            <%= render 'form' %>
          </div>
        </div>

        <%= javascript_include_tag "application" %>
        <%= javascript_include_tag "nested_form" %>
        <%= yield :javascript_includes %>
    </body>
</html>

app/views/courses/show.html.erb
<%= render "header" %>

<p id="notice"><%= notice %></p>

<% active_assignments = @assignments.select{|a| a.to_do(current_user).length > 0} %>
<% if active_assignments.length > 0 %>
    <% active_assignments.sort_by{|a| a.submission_due }.each do |assignment| %>
        <a class="assgnToDoName" href="/courses/<%= @course.id %>/assignments/<%= assignment.id %>"><h3><%= assignment.name %> Tasks</h3></a>
        <% if assignment.to_do(current_user).length == 0 then %>
            <div class='allTasksCompleted'>All tasks for <%= assignment.name %> completed.</div>
        <% end %>
        <% assignment.to_do(current_user).each do |task| %>
            <div class="toDoUl">
              <% hours_remain = ((task[:time] - Time.zone.now) / 1.hour).round %>
              <% remaining =  ' (' +
                      (hours_remain.abs < 25 ? pluralize(hours_remain, 'hour', 'hours') :
                              pluralize(hours_remain/24, 'day', 'days')) +
                      ' left)' %>
              <% if task[:action] == :submit %>
                  <li><a href="/courses/<%= @course.id %>/assignments/<%= assignment.id %>" >
                    <div class='a_name'>Submit <%= assignment.name + (task[:team] ? ' for ' + task[:team] : '') %> </div>
                    by <%= task[:time].strftime('%A (%-m/%-d) at %I:%M %p') + remaining  %>
                  </a></li>
              <% else %>
                  <li><a href="/courses/<%= @course.id %>/assignments/<%= assignment.id %>/submissions/<%= task[:submission_id] %>" >
                    <div class='a_name'>Complete Review <%= task[:index].to_s %></div>
                    by <%= task[:time].strftime('%A (%-m/%-d) at %I:%M %p') + remaining  %>

                  </a></li>
              <% end %>
            </div>
        <% end %>
    <% end %>
<% else %>
    There is nothing to do.
<% end %>